[[plugins]]
package = "netlify-plugin-cache"

[plugins.inputs]
paths = [".cache"]

[[redirects]]
from = "/feed"
to = "/feed.xml"

[[redirects]]
from = "/feed/?type=rss"
to = "/feed.xml"

[[redirects]]
from = "/feed?type=rss"
to = "/feed.xml"
